apiVersion: v1
kind: Service
metadata:
  name: postservice-application
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: postservice-application
  type: LoadBalancer